### ISSUE TITLE
貌似第四章和第六章还没有翻译完

### ISSUE THREAD

**Issue by lujun9972** [Voidly/Parallel-Programming-with-Python#11]
我看有些文件是空的....
目前我正在尝试补全第四章的那些内容

**Comment by Voidly** [comment]
赞！我们三个当初分工合作的，，负责第四章和第六章的人当时忙着做毕设找工作什么的，所以可能没有翻译完，欢迎加入！

**Comment by lujun9972** [comment]
:smile:谢谢

话说，有什么比较入门的python并发的书推荐吗？ 感觉现在这本书写的比较简略。

**Comment by Voidly** [comment]
官方文档，python标准库，High Performance Python，Python Parallel Programming Cookbook

**Comment by lujun9972** [comment]
十分感谢
